### ISSUE TITLE
UN-draw?

### ISSUE THREAD

**Issue by ConorOHaleck** [ofHillsAndLakes/Daemon-Souls#10]
Wondering how I could best implement a function to take away an item (like when a player picks one up) that doesn't destroy everything. Should I just punt the thing to some ridiculous position like -50,000, and bring it back if the player drops it? That's the best way I can see with the current code.

**Comment by golbette** [comment]
The best way I can think of is to have it in a collection, and remove it
from that collection once it's used. If you're only drawing/updating
members of the collection it'll stop being drawn or updated entirely.

**Comment by golbette** [comment]
Monsters undraw when dead in the latest build so this probably isn't an issue any more. Closed
