### ISSUE TITLE
Yo Sam

### ISSUE THREAD

**Issue by LaughingBarista** [ofHillsAndLakes/Daemon-Souls#11]
May I take you up on your offer? I'm pulling out my hair getting my code to function with dungeon generation, etc.

**Comment by RobertBohlman** [comment]
Hopefully you get that working soon, I had to get creative for what to use as a targeting reticle.

![image](https://cloud.githubusercontent.com/assets/12433391/15808241/9fb98ba4-2b27-11e6-963b-b4f7950c7405.png)

**Comment by LaughingBarista** [comment]
Hahah I'm trying! But, for example, when changing the DUNGEON_FLOOR variables in Sprites, I manage to break the camera movement..

**Comment by RobertBohlman** [comment]
I wouldn't know, since I haven't worked with the assets or camera at all.

**Comment by LaughingBarista** [comment]
Indeed. What I might do is just set up all the appropriate assets needed in the sprites class and let you and Sam put them in the necessary points in your code, since you know it better than I.

**Comment by golbette** [comment]
What do you need? I'm not entirely sure by the context of the message other than there's a problem with sprites.

**Comment by LaughingBarista** [comment]
I'll merge what I've got. Basically, I the images were completely wrong when using Textures but perfect while using TextureRegions. That being said, I've had to go through and change a lot of things to reflect the use of textureRegions as opposed to textures. But there is a portion in Map that I'm afraid to mess with .. public void Draw(SpriteBatch bat).

**Comment by golbette** [comment]
No problem. How do we draw with a TextureRegion? Is there a version of the Draw() method that takes one directly? I've been a little fuzzy on that.

**Comment by LaughingBarista** [comment]
Yes. The Draw() methods are all very similar between Texture and TextureRegion.. they just aren't quite the same.. I have no idea why they do that, but oh well..

**Comment by RobertBohlman** [comment]
Shouldn't you be able to just replace the ones I set up to draw the placeholders?

**Comment by LaughingBarista** [comment]
I did already do yours, but with the amount of trouble I've had when touching anything related to Sam's dungeon generation, I figured it would probably be safest if the creator of that content did it.

**Comment by golbette** [comment]
Ahhh, I see what's up. Should be an easy fix, will do.

**Comment by LaughingBarista** [comment]
Thank you!

**Comment by golbette** [comment]
Are there any floor indexes which correspond to a blank tile? Also, is there a reason we aren't just making all the texture atlases publicly accessible and asking for their textures directly by key rather than through a dummy object?

**Comment by LaughingBarista** [comment]
No, I was just trying to keep the format the same as what you had working. And no, there is no good reason for all the dummy objects, it is moreso a reflection of my confusion with putting this whole thing together. There is a lot of room for streamlining, I'll admit. The general idea that I had was to keep everything loaded from the atlas, and return a random tile for each dungeon's floor, wall, etc, keeping things ever changing, but it might also look rather silly.

**Comment by LaughingBarista** [comment]
Do you think it would be worthwhile to slim down my code and make it a bit leaner?

**Comment by golbette** [comment]
I wouldn't worry too much about it! We've got what we need unless Robert or Connor says otherwise.

**Comment by RobertBohlman** [comment]
I was planning to do a pass later and smooth things out as like a last step process, but it depends on how we're doing for time.
