### ISSUE TITLE
Collison done, enemies too?

### ISSUE THREAD

**Issue by RobertBohlman** [ofHillsAndLakes/Daemon-Souls#12]
Got collision working for players, do we need it implemented for Ai as well? I figured it would be different since the monster use different logic to move.

**Comment by ConorOHaleck** [comment]
Ideally, Collision would be handled in Creature so it works across everything (everything accepts not moving to an unpathable tile). If there are only four movements, could we put those in Creature and have collision checks and the like, with movement methods from Player simply calling those methods from the Parent class? That was how I was going to implement it in monsters. Of course, I still could, and players just move differently...

**Comment by RobertBohlman** [comment]
Well the reason I say that is because monsters move in relation to the player, so including a check for collision there seems like it would be easier, if you see how I threw together the basic movement for the test imp in enemy that's what I mean.

**Comment by ConorOHaleck** [comment]
Easy enough to compartmentalize. Monsters are extremely, extremely modular, so I'll probably pare everything I can down to the basic Monster class and spread out from there.

**Comment by RobertBohlman** [comment]
Yeah I was planning on letting you handle it but figured I'd check first since I was already doing player collision.

**Comment by LaughingBarista** [comment]
Out of curiosity, how exactly did we want to handle that in regards to tiles? Initially, I had created Tile to be an abstract class that extended Entity, and instantiated objects of type Floor and Wall that already had the appropriate boolean canCollide value set in the constructors. I still have the constructor to do so and can make some changes to Assets to reflect the appropriate values of canCollide, if that is being used to detect collision.

**Comment by RobertBohlman** [comment]
I think that's fine, the only thing I added was setting conCollide to true for any tile that had a monster standing in it,

**Comment by LaughingBarista** [comment]
Smart. Sounds good, will do. Otherwise, what's next? According to schedule, I still need to get the animations to actually run. I also have UI work to do. I will make the minor changes in Assets. Should I just make a bunch of monster and item images in Sprites for you guys to use? (Which I might just get new art work for.. our existing monsters are pretty fugly..)

**Comment by RobertBohlman** [comment]
Whatever works to be honest, we just need something presentable. We can always change them later, but remember the goal is to have this thing show-able by Tuesday.
