### ISSUE TITLE
Item Pickup Issues.

### ISSUE THREAD

**Issue by RobertBohlman** [ofHillsAndLakes/Daemon-Souls#13]
Connor, the code you wrote to pick up items when the player walks over them seems to cause a null-pointer exception when the tile is empty. Did this happen with you?

Edit: I fixed it, but I had to edit the code slightly, fine if I publish that?

**Comment by golbette** [comment]
I also had to fix this before I ran today. Make sure to test your code before you push it, guys :P 

Go ahead and push your fix ASAP so I can pull it without any merge conflicts.

**Comment by RobertBohlman** [comment]
Pushed both fixes just now.
