### ISSUE TITLE
Movement bugs - player moves 2 graphical tiles at once

### ISSUE THREAD

**Issue by golbette** [ofHillsAndLakes/Daemon-Souls#14]
The player almost always seems to move two tiles forward graphically instead of one. I'm not sure if this is affecting how the player is being registered by the tile system logically. Someone more familiar than me with the movement infrastructure should probably look at this.

**Comment by RobertBohlman** [comment]
Huh. I didn't notice this until I turned on the print statements for position, I'm looking into it atm.

**Comment by RobertBohlman** [comment]
Naaah see, it was just your imagination.

![tub8cuo](https://cloud.githubusercontent.com/assets/12433391/15809176/b15780ec-2b3f-11e6-99d2-af5fb41d483e.png)

**Comment by golbette** [comment]
![hqdefault](https://cloud.githubusercontent.com/assets/16601707/15809463/a547335e-2b46-11e6-9fd7-8ee0d0803a66.jpg)
