### ISSUE TITLE
Room population

### ISSUE THREAD

**Issue by golbette** [ofHillsAndLakes/Daemon-Souls#16]
Hey guys, there's a new function in Map called Populate() that lets you pass an arraylist of monsters and it'll spawn one per room and hallway inside of the map. If you want these monsters to actually do anything you'll have to iterate through that list and do whatever functions they have to update them. 

I've also noticed that the rooms feel really huge compared to the player size. Would you like to see the dungeon floors reduced in size, y/n?

**Comment by ConorOHaleck** [comment]
Yuss, I literally just checked this before I want to bed. That's the crux of the issue I was having with monster, was deciding how their activation would be called. I was gonna ask the question here, but... question answered.

As far as dungeons go, is there a way to make rooms smaller but keep floors the same size? I guess that would get onerous if there were an appropriate number of wandering monsters. Floor size is easy to tweak though, right? Just one-two digits in the DungeonGenerator/Tree classes?

**Comment by golbette** [comment]
If you increase the number of splits (depth) it'll give you more smaller
rooms. Just don't make it too large or you risk running out of memory.

**Comment by golbette** [comment]
I reduced the size of rooms in the latest push, and now there are more rooms. The dungeon is still the same size. I think it has a good 'game feel' so I'll leave it up to judgement. 

Leaving this open for any questions or concerns about using the new method.

**Comment by LaughingBarista** [comment]
I think that it all looks great! Good job!
