### ISSUE TITLE
Combat log help

### ISSUE THREAD

**Issue by RobertBohlman** [ofHillsAndLakes/Daemon-Souls#17]
So It appears I was a bit mistaken on how easy the combat log was going to be. I'm having a hard time figuring out what kind of object to use since TextField and TextTooltip need these things called skins which rely on special files. If anyone has an idea on what I should be looking towards, that would be appreciated. In the meantime, I'll be working on the other stuff I was trying to get done.

**Comment by LaughingBarista** [comment]
So, I've already got a skin going if you want to continue using it, but the code I have currently is broken. I'll push it as soon as it's functional.

**Comment by RobertBohlman** [comment]
Alright let me know when it gets fixed and I'll try it out.

**Comment by LaughingBarista** [comment]
I find it surprising, but my trouble maker here is actually getting the player instantiated appropriately.

**Comment by RobertBohlman** [comment]
Oh, I changed it to a wizard because I was messing with targeting, setting it back to what you had it might fix it.

**Comment by LaughingBarista** [comment]
Well yeah, but I can't make the declaration in MyGdxGame, before the create() method. I have to find a way to instantiate the player as a global variable of the appropriate class. But the reticle is throwing errors when I do because it has no mapX and mapY values.

**Comment by RobertBohlman** [comment]
Uhhh, try setting mapX and mapY to zero in the reticle constructor, should work. I think it will still update.

**Comment by LaughingBarista** [comment]
It is.. and so are the testPlayer.mapX and testPlayer.mapY that it refers to.
![capture](https://cloud.githubusercontent.com/assets/15771896/15844392/cf6d3a2e-2c1e-11e6-86b1-29438d987fb9.PNG)

**Comment by RobertBohlman** [comment]
Yeah if you get rid of those two lines in the constructor. Try that.

**Comment by RobertBohlman** [comment]
So David you said you had a skin going but I don't know how to access it. Is it within a certain class?

**Comment by LaughingBarista** [comment]
Yes. Currently I'm working on a separate HUD class to house the game overlay. We can add the combat log code to it, if that sounds good to you.

**Comment by RobertBohlman** [comment]
Well the problem I'm having is that I can't actually make a combat log without a skin.

**Comment by LaughingBarista** [comment]
Here, I'll submit what I'm currently working on to the UI branch, but it's woefully incomplete. Also, we apparently didn't have class today and were not meeting up. I didn't know that.. hahah.

**Comment by RobertBohlman** [comment]
Well yeah it's finals week.

**Comment by RobertBohlman** [comment]
But you made the skin in the UI branch?

**Comment by LaughingBarista** [comment]
Ah.. That makes sense. Yes, I had made the skin in the UI Class of the UI branch. The thing is, the skin seems to be just a container for created configurations (like button styles, etc.). It is more helpful if we were repeating button styles. But you should take a look at how I set it up, as you'll probably have to follow a similar format.

**Comment by RobertBohlman** [comment]
I'd prefer to be able to just use it for both consistency and ease, but I'm studying for my physics final atm, I can take a look in a bit.

**Comment by LaughingBarista** [comment]
No worries, I'll keep working on the HUD class and update the branch periodically. As for the problems with the beginning UI, however, I feel I've tried everything I can think of. Maybe once I get done with HUD I'll re approach it, but I've had no new thoughts of how to fix it.

**Comment by RobertBohlman** [comment]
I saw Sam saying something about the way I was handling classes. Have you tried instantiating testPlayer as a Player at the start, and then downcasting it to the appropriate class once the selection was made?

**Comment by LaughingBarista** [comment]
Yes. That is basically the main angle I've been working from, but it never works.

**Comment by golbette** [comment]
Hey I'm just poking in here to let you know that the issues with player class selection (and the start menu in general) have been, afaict, fixed. You should be able to start on the HUD/combat log any time you're ready now

**Comment by LaughingBarista** [comment]
Oh yes. I realize. I appreciate it! I've primarily been trying to figure out how to draw the HUD over the game without breaking ranged abilities.

**Comment by RobertBohlman** [comment]
What's it doing to ranged abilities?

**Comment by LaughingBarista** [comment]
Here, see for yourself. I'll upload it to another branch so it doesn't break anything in master.

**Comment by LaughingBarista** [comment]
... or maybe it'll actually accidentally go to the master branch. sigh.

**Comment by RobertBohlman** [comment]
So I was thinking, are you currently doing this on your laptop?

**Comment by LaughingBarista** [comment]
No, desktop. What's up?

**Comment by RobertBohlman** [comment]
Damn, I was wondering if it would be possible to just push deployment to Wednesday night (since we still have nothing from Connor) and bring the program tomorrow so we can see if the three of us can figure this out. I say this because I don't know about you, but I'm hitting a major wall here.

**Comment by LaughingBarista** [comment]
I can try to have it run on my laptop, but I'm not sure the laptop could survive it to be honest. But yeah; whatever works best. I should just mention, tomorrow night I have my last final, then I work 4:30 am to 12:30 pm on Thursday..

**Comment by RobertBohlman** [comment]
Yeah, I'm not sure if it was the best idea if you weren't already confident in the laptop, I'm just trying to think of ideas right now because I feel like I'm not getting anywhere.

**Comment by LaughingBarista** [comment]
Has anybody sought Connor out to see what's going on?

**Comment by RobertBohlman** [comment]
I sent him a message on Canvas earlier today, no response.

**Comment by LaughingBarista** [comment]
Hmmm.. so what are we planning to do if his portion of work is incomplete?

**Comment by RobertBohlman** [comment]
Believe it or not I actually trust his dumb ass to get something done, albeit it will probably be last minute.... As for the log by the way, I just had a slight idea as for how to get it to function properly, however it would take a lot of messing with so I think It might have to wait until tomorrow, as early as I can tomorrow, but still tomorrow.

**Comment by LaughingBarista** [comment]
Okay. Maybe I'll also pull off, try to get a good night's sleep and start early tomorrow as well. For some reason I really have troubles with proper display of these stupid UI/HUD portions. So where do we want to meet up at noon?

**Comment by RobertBohlman** [comment]
I would still like to yes.

**Comment by LaughingBarista** [comment]
Good, but I meant where? The usual class foyer?

**Comment by RobertBohlman** [comment]
Uh, how about the information commons in that building?

**Comment by LaughingBarista** [comment]
Sure thing. I'll see you then.
