### ISSUE TITLE
Gradle problems.

### ISSUE THREAD

**Issue by RobertBohlman** [ofHillsAndLakes/Daemon-Souls#2]
So, I have literally zero experience with gradle and seem to be having problems getting it properly installed on my eclipse. Either I'm getting the wrong version or something else is screwing up, I don't know. Can someone tell me the steps they went through to get the necessary gradle plugins to work for the project? It would also help if anyone had a link to the website they got the plugins from.

**Comment by golbette** [comment]
Mine came installed and working with my copy of Eclipse Mars from their
normal website. If gradle is installed correctly you should just be able to
do Import->Gradle Project and everything will work.

**Comment by RobertBohlman** [comment]
I just did a fresh install of mars on my computer because of something else screwing up, so I'll try it.

**Comment by RobertBohlman** [comment]
Alright I see the option to import a gradle project. I'll give it a shot tomorrow though, stayed up waaay to late last night.

**Comment by RobertBohlman** [comment]
Okay, so I'm trying to wrap my head around this. From what I understand, gradle needs to compile and test the code, but I'm trying to distinguish that from when I'm actually running the program in eclipse. Should I be trying to run the program directly using the desktop launcher class, since whenever I do it keeps throwing various exceptions that seem to be both missing files (which are there in their folders) and something with initialization.

http://i.imgur.com/1EJUW6N.png

Update. I fixed the first issue but the program can't seem to load the images from the asset folder
Update 2: Alright. I THINK I got it, seemed to be something with my run configuration.

**Comment by golbette** [comment]
Just got in. Is this closed because you solved the problem? If not, I can
help.

**Comment by RobertBohlman** [comment]
Yeah technical difficulties are resolved, now I'm just tinkering with the program itself. Got a basic tile movement and turn system set up (very informal atm) and am just working on code for boundaries to prevent you from walking through walls (or off screen in this case). After that planning on working of targeting things and using skills on them. Not sure how far I'll get but that's my goal.

**Comment by golbette** [comment]
All right. I've got early-stage dungeon generation working, and that'll
include markers for tiles that are passable or not. Right now I'm working
on feeding the algorithm into the map and tile data structures which
actually, y'know, render the dungeon. You should be able to git pull what
I've made so far if you want to see it, but nothing's actually functional
beyond some debug logging that makes sure my binary trees aren't crashing
and are actually shaped right.

**Comment by RobertBohlman** [comment]
Ah shit I wish I read that BEFORE I just pushed changes, no worries nothing got overwritten, but yeah might have to delete those two extra classes I made, oh well.

**Comment by RobertBohlman** [comment]
Or.... It didn't appear to have done anything? Well I'll just check back later and see if anything's changed.

Edit: Nvm there it is.
