### ISSUE TITLE
Pre-Presentation Meeting

### ISSUE THREAD

**Issue by RobertBohlman** [ofHillsAndLakes/Daemon-Souls#21]
Would it still be possible for us to meet up with a working program tomorrow so we can review it in person and make sure we're still good to go? I'd like you guys to list some times you would be free at the college so we can figure something out.

**Comment by LaughingBarista** [comment]
I am free all day long, with the exception of from 5pm to 8pm.

**Comment by golbette** [comment]
Likewise, i'm free until 5PM-8PM tomorrow.

**Comment by RobertBohlman** [comment]
Alright, well my final is early in the morning, but does noon sound alright for time?

**Comment by LaughingBarista** [comment]
Sure. That's fine with me.

**Comment by golbette** [comment]
I'll be there.

**Comment by ConorOHaleck** [comment]
I will too, of course.

**Comment by golbette** [comment]
Honestly I assumed you wouldn't be there. :100: :fire:

**Comment by ConorOHaleck** [comment]
I'm done with all my finals now (and what finals they were!). This is the only thing on my plate. I'm in it to finish the fight.

**Comment by LaughingBarista** [comment]
Wooo! :boom:
