### ISSUE TITLE
Latest Build: Test?

### ISSUE THREAD

**Issue by ConorOHaleck** [ofHillsAndLakes/Daemon-Souls#23]
Is anyone else having trouble getting the latest build to actually open? Maybe I'm just being a noodle, but Player's constructor is apparently trying to assign a Texture to a Texture Map, and Eclipse is giving me a mean look when I try to open the tester. Did I miss something obvious?

**Comment by golbette** [comment]
Working fine here. You might have a corrupted project folder. Try 'git pull origin master' or a clean clone of the repository, whichever gets you a project that compiles and runs as-is.

**Comment by ConorOHaleck** [comment]
Beautiful. Okay, now about those monsters....
