### ISSUE TITLE
Clarification of dungeon population

### ISSUE THREAD

**Issue by golbette** [ofHillsAndLakes/Daemon-Souls#24]
**EDIT: This post isn't relevant any more. Please don't try and use information from this post when using the Map class.**

I was wrong, there are actually no monsters in the dungeon whatsoever, because the current iteration of it is not calling the Populate() method at all. (I took it out after testing.) The method should still work as nothing inside it has changed for days

**Comment by ConorOHaleck** [comment]
Where is Populate() again? I can't find it anywhere inside the project...

**Comment by golbette** [comment]
Map.populateRooms(ArrayList<Creature> Monsters)

thanks avast

**Comment by golbette** [comment]
Closed because the method has totally changed and this is way outdated.
