### ISSUE TITLE
Bug: Animations Causing Freezes.

### ISSUE THREAD

**Issue by RobertBohlman** [ofHillsAndLakes/Daemon-Souls#26]
Making an issue here for ease of discussion.

**Comment by golbette** [comment]
Is it a while loop? Change it to an if if so.

**Comment by RobertBohlman** [comment]
It's not in a while loop, though i don't know what the method itself does. If I try to use the skill however, the program gets to the line where it calls the animate method and the whole thing freezes, the libgdx window itself stops responding. Also the vague OP was because I brought this up in a comment on one of David's commits.

Edit: Okay after analyzing the Sprites.effectAnimate() method I can conclude there is a while loop. I would fix it but I'm not entirely sure how. I suppose I can mess with it a bit once my other stuff is done.

**Comment by LaughingBarista** [comment]
No worries! I just got back and can play with it too. Hopefully I can provide the break statement you need. :smile:

**Comment by RobertBohlman** [comment]
Idk I'd recommend avoiding while and break statements if you could, it's generally considered poor practice from what I understand.

**Comment by LaughingBarista** [comment]
Is it really? That makes me sad, I love to use them.. By chance is the ice lance up and running? Nevermind about the ice lance.. it's broken too. (animation-wise)

**Comment by RobertBohlman** [comment]
I fixed both the spells so they work without the animations. Btw about to make a push, I'll detail the changes in the push itself, and I'll need your help with something.

**Comment by golbette** [comment]
Belatedly, the issue with while loops in libgdx is that render() is itself called every frame, so if you put anything in a while loop that's waiting for player input or frames to pass, it'll loop indefinitely, because you're processing the same frame forever. 

So for instance, if I have a 5-frame animation in my render loop, rather than going while(frame = whatever...) I'd want to use something like if(frame = whatever...) and increment my frame count inside of the if statement. 

You could probably emulate this with break; statements, but it'd be kinda messy.

**Comment by LaughingBarista** [comment]
Sure thing Robert. I appreciate the explanation Sam. That helps make sense of my errors quite a lot! I do also currently have something that works for the animation without breaking anything, it just renders very very quickly.

**Comment by LaughingBarista** [comment]
Okay everybody;
I have done the things I was responsible for today.. But I think our game would have a lot more feeling and life if I could get these blasted animations up. The thing is, they render way too quickly. I could write the appropriate code into each section, if you guys like. But, I work in six hours. That being said you guys can see if you can get it to render reasonably, maybe by repeating more frames within the animation itself(?), or I can just not even worry about it. What do you guys think?

**Comment by RobertBohlman** [comment]
I'm not sure, I think if push comes to shove we just leave it. Though I do need you (or someone, I've just been having a hard time doing it myself) to draw a bloody square where the stair tile is and remove the placeholder text.
