### ISSUE TITLE
Powerpoint

### ISSUE THREAD

**Issue by ConorOHaleck** [ofHillsAndLakes/Daemon-Souls#27]
Apparently we will "Probably want a few powerpoint slides" That seems very vague. Do we actually need one, or is it going to be needlessly complicated?

**Comment by RobertBohlman** [comment]
It's Straayer, you know the answer to that question about as much as anyone else will.

**Comment by ConorOHaleck** [comment]
I'm just gonna focus on getting this to all work. I can fret about the powerpoint later.

**Comment by RobertBohlman** [comment]
Yeah i agree.

**Comment by RobertBohlman** [comment]
Hey Connor just a heads up looks like David made a method called slowYourRollBro in MyGdxGame to wait between turns so no need to make your own.

**Comment by ConorOHaleck** [comment]
Yeah right now I'm trying to get Draw to not break on iterating with all these monsters...

**Comment by golbette** [comment]
On it.

**Comment by golbette** [comment]
We have 'a few powerpoint slides' now. https://docs.google.com/presentation/d/1douW_muQyrzF211jHnKMSOY3zL4Nvf3QeQDuylLCqtc/edit?usp=sharing
