### ISSUE TITLE
Weird Detection Issues

### ISSUE THREAD

**Issue by RobertBohlman** [ofHillsAndLakes/Daemon-Souls#28]
So, there seems to be a lot of weird offset problems with where creatures are located. I don't know if this is a glitch with the current testing enemy or not, but I cant seem to hit it properly with normal melee hits. It seems to detect my position fine, so maybe it will work once we have real monsters, but can I ask if anyone messed with anything that would change how the game reads the positions of things on the grid? Because when I did melee and ranged combat last weekend it worked fine.

**Comment by golbette** [comment]
The only thing I've done is modify the logic used to move and place the player, I haven't touched enemies at all. Maybe have the monster as well as the player return their positions each turn?

**Comment by RobertBohlman** [comment]
I suppose, I planned on waiting and messing around with the monsters Connor put in since the code was likely to be different anyways.

**Comment by golbette** [comment]
Yeah, I think if Connor was...I _hope_ if connor is having issues with enemy position detection, he'd have said something by now.

By the way, I'm home, so let me know if there's any loose ends or outstanding problems I can help with. I've been catching up on issues but most of it looks like workflows I shouldn't interrupt with any of my own code so far without notice.

**Comment by ConorOHaleck** [comment]
I'm not having problems with enemy detection, I'm having problems with getting them all the values they need and getting player the values from them. I've just about got it licked I think.

**Comment by golbette** [comment]
All right. If you get super stuck on anything don't be afraid to post, since both Robert and I basically built the whole movement/tile system together-ish and can probably answer any questions about functions and such.

**Comment by RobertBohlman** [comment]
I'm glad things are working on your end becuase here they are..... Well... Straight fucked.
![untitled](https://cloud.githubusercontent.com/assets/12433391/15917753/3feaa2c8-2db4-11e6-9136-83028cb254fc.png)

**Comment by ConorOHaleck** [comment]
The biggest problem right now (short of any actual values adjustments) is getting things to update in the correct order. Enemies need to be given a player object in order to move towards you, but I have to instantiate all the enemies before the player is actually created, etc. I'm getting through it.

**Comment by golbette** [comment]
Can you feed the enemies a dummy player, and then update that dummy player var whenever the player gets instantiated during INIT_PLAYER?

**Comment by ConorOHaleck** [comment]
That's exactly what I did, with a forEach

**Comment by golbette** [comment]
Welp,

**Comment by ConorOHaleck** [comment]
Also I changed slow your roll bro to take a float, because pausing for 1 second is honestly too long.

**Comment by ConorOHaleck** [comment]
Wait no that's dumb, just changed it back but reduced the multiplier to 100, so now passing it a 10 is one second. Much better.

**Comment by LaughingBarista** [comment]
Yeah I really don't blame you. 1 second seems pretty harmless at first but at runtime, it seems an eternity.

**Comment by golbette** [comment]
Fixed, closing
