### ISSUE TITLE
Movement struggles

### ISSUE THREAD

**Issue by ConorOHaleck** [ofHillsAndLakes/Daemon-Souls#29]
I figured out why nothing was working right, especially my Proximity detectors...

mapX and mapY in player stated "where we are in worldspace" but they're actually never used or updated. So I'm hotswapping my Monster stuff to use pixels instead. Any help you guys could give me on this point would be great, because I have to make sure this goes off nicely. Is there anything I should know about updating/redrawing things concerning pixels.

**Comment by RobertBohlman** [comment]
The "grid" that's used for position is 200X200 squares or "units". So what you need to do is if you're moving, multiply the number of squares you want to move by tile.width/height (32). Likewise, if you're using something like getTileAt(xpos, ypos), you need to divide the inputs by tile.width/height (so, xpos/Tile.WIDTH, ypos/Tile.HEIGHT) to get the grid values that the methods use.

**Comment by ConorOHaleck** [comment]
Yeah, that unit system is actually what I thought I was using before, because I thought mapX/mapY actually got updated. The wonders of Find + Replace allowed me to at least sort out Chase/Flee quickly.

**Comment by RobertBohlman** [comment]
Yeah I was updating mapX and mapY in the player movement, but I'm not sure they were used for anything.

**Comment by ConorOHaleck** [comment]
Well, in my testing I discovered they weren't being updated. At least, they stayed at 0,0 as far as I could tell, no matter what.

**Comment by RobertBohlman** [comment]
Nevermind just checked, looked like I (or someone) removed it.

**Comment by RobertBohlman** [comment]
Actually... _Ahem_ I INVOKE SAM! Yo Sam are mapX and mapY still being used for anything on your end?

**Comment by ConorOHaleck** [comment]
I did a ctrl+F, I couldn't find a single place where they were used, so I doubt it.

**Comment by golbette** [comment]
I APPEAR! The answer should be no.

**Comment by RobertBohlman** [comment]
Alright cool.

**Comment by golbette** [comment]
Yeah, sorry about all that, it looks like we basically subverted the need for mapX/mapY by just...doing coefficients on the graphical X/Y

**Comment by RobertBohlman** [comment]
Okay, I was just wondering if it had anything to do with our movement oddities.

**Comment by golbette** [comment]
Not that I'm aware of.

**Comment by golbette** [comment]
Fixed now.
