### ISSUE TITLE
Can't Push/Pull

### ISSUE THREAD

**Issue by ConorOHaleck** [ofHillsAndLakes/Daemon-Souls#32]
I've been trying to merge my Monster stuff over to the master branch, and it's saying it can't merge automatically. Furthermore, trying to sync the other changes people have made also fails. Apparently I have to commit this manually? Any advice would be appreciated.

**Comment by RobertBohlman** [comment]
I get the feeling Sam might need to do the command line magic stuff again.

**Comment by golbette** [comment]
I'll take a look.

**Comment by golbette** [comment]
Dunno what you're trying to do, but this is happening when I try to run the game.

http://puu.sh/pm7KH/3f3fb77299.png

Looks like a math error where the monster tries to call tiles in the map that don't exist when moving. 

Make sure that all inputs to getTileAt() are in world space (e.g., not multiples of 32). I tried removing the *32 coefficient from your code, but it just causes monsters to not appear. Unless they've never been appearing.

**Comment by ConorOHaleck** [comment]
Well I would look into that, but something in the merging/unmerging/not-being-able-to-merging has messed up my local code. I have some stuff about the "HUD" that I don't actually have access to or have anything from. Also, updateLog references even though that apparently isn't a method. I'm just going to copy all the code I changed from the git client, do a fresh pull, and put that stuff in.

**Comment by RobertBohlman** [comment]
updateLog most certainly is a method, I wrote it at the bottom of MyGdxGame.

**Comment by golbette** [comment]
Your local code is messed up because git put in all the merge conflicts into the code file for you to edit as you please. I've already done that part, so discard whatever you have and update your master branch. 

In the future, when it does this, you can just unfuck the code and then tell git to add the now-unscrewed file, and that'll solve the merge conflict! It's actually a pretty cool feature (compared to SVN) once you're used to it, uh, breaking your code sometimes.

**Comment by ConorOHaleck** [comment]
Yeah, managed to get the updated master to work (Christ on roller skates that was annoying). I'll work on whatever problems there are now. When you say you can't see monsters, do you mean you can't find any? Because the cheap tester population I used has like, 3 monsters total.

**Comment by golbette** [comment]
If you passed a list of 3 monsters, it should still populate very room in the dungeon with 1 of those 3 monsters if you're calling populateRooms(). 

EDIT: Or it would, except I just realized pointers in java mean that's _not_ true. You will actually only get 3 monsters in the entire dungeon with a list 3 monsters long! 

Either I don't see anything at all (when I don't have the *32 coefficient in the line) or there are crashes sooner than I can check (when I do have the *32 coefficient in the line).

**Comment by LaughingBarista** [comment]
Were you updating your code through Eclipse's refresh mechanism, Connor?

**Comment by ConorOHaleck** [comment]
I was doing something wrong, I'm sure. But it was git that said I couldn't push, and then that I couldn't pull after that.

Either way, I'm still working on some monstery stuff, including changing the population. The git commit bug set me back some serious time

EDIT: I thought it was something like that! Heh, anyways yeah, that means I need a way to generate a lot of monsters, which I'll do.

**Comment by golbette** [comment]
'git reset --hard HEAD' should pull you out of any failed merges and back to the old working repository in the future.

**Comment by RobertBohlman** [comment]
Guuuuuuhhhhh this stair crap is driving me crazy. Can someone tell my why this method is seemingly generating stairs in crazy positions like 3000, 2345?

![image](https://cloud.githubusercontent.com/assets/12433391/15919326/29eab0c4-2dc5-11e6-8e2a-6f7b5ba74d10.png)

**Comment by RobertBohlman** [comment]
Wait

**Comment by RobertBohlman** [comment]
Goddamn it.

**Comment by golbette** [comment]
You multiplied by 32/TILE_WIDTH before asking getTileAt(), didn't you

**Comment by RobertBohlman** [comment]
Gentlemen I found the stairs

![image](https://cloud.githubusercontent.com/assets/12433391/15919365/8a26f240-2dc5-11e6-8db1-6dc895e75243.png)

**Comment by golbette** [comment]
@ofHillsAndLakes , it looks like I can't deep copy the monster arraylist so you'll just have to pump it full of as many monsters as you'd like spawned.

**Comment by RobertBohlman** [comment]
No for some reason someone _cough_ _cough_ replaced that little line in my else clause that rerolled the position if it was unpathable or out of the map.

**Comment by golbette** [comment]
I'll take full responsibility as soon as I'm back from delivering my hospitalized roommate a cellphone charger. 

...No, I'm serious.

**Comment by ConorOHaleck** [comment]
Lol. By that point I'll have generateHorde() fully done, which will let me bughunt the crap out of any Monster() that needs bughunting.

**Comment by golbette** [comment]
You better, or else, I'll, uh!! uh!! write something mean in a comment! yeah

**Comment by RobertBohlman** [comment]
Connor how did you fix your merge issues because I think I'm running into the same thing.

**Comment by ConorOHaleck** [comment]
I had to wait for Sam to push (pull?) my change to the master branch, then pull that using the command line to force it through, manually deleting the conflicts that resulted.

It wasn't fun.

**Comment by RobertBohlman** [comment]
Alright well whatever I just did either fixed it or fucked everything. I'll get back to you when my heart starts back up.

**Comment by ConorOHaleck** [comment]
I know the feeling.

**Comment by RobertBohlman** [comment]
Okay I think were good, I'm going to create a new issue with the notes from my last push because I want to make sure people are aware of some things.

**Comment by LaughingBarista** [comment]
... I'm sorry Robert.. I just realized that I was your culprit.. I misinterpreted your code..

**Comment by RobertBohlman** [comment]
I KNEW IT! Lol it's cool.

**Comment by LaughingBarista** [comment]
Hah, all you'd have to do is look at the change log for my push after adding the stairs. I have nowhere to hide in my guilt, friend.

**Comment by golbette** [comment]
Hopefully there won't be any more git issues as we're gearing up for deploy as I write, but if anyone desperately needs to unscrew their git just pop open another issue.
