### ISSUE TITLE
Notes from last push, some bugs and stuff.

### ISSUE THREAD

**Issue by RobertBohlman** [ofHillsAndLakes/Daemon-Souls#33]
Fixed a bug where the fireball reticle was shifted to the right (may or
may not have been caused by me). Implemented code for stairs, I need
someone to replace that placeholder text with an actual stair block.

*Bug: Sometimes when I call generateFloor you spawn inside a wall.

**Comment by LaughingBarista** [comment]
... I will try to fix your stairs (the right way this time).

**Comment by RobertBohlman** [comment]
Thanks, literally I just need you to draw a little square over the tile.

**Comment by LaughingBarista** [comment]
Okay. Your stairs are there and fixed. Goodnight guys! I'll see you all tomorrow!

**Comment by RobertBohlman** [comment]
Thanks a ton man.
