### ISSUE TITLE
That collision issue

### ISSUE THREAD

**Issue by ConorOHaleck** [ofHillsAndLakes/Daemon-Souls#34]
I'm having the same problem with monster collision, in that they appear 1 tile left of where they "actually" are, and I can't seem to hit them. I'll try to bug hunt it now, but if you figured it out in the meantime, I'd appreciate anything you found out.

Also the Hero can't seem to die...

**Comment by RobertBohlman** [comment]
Oh crap I thought I forgot something.

**Comment by ConorOHaleck** [comment]
On the plus side, monsters are showing up and running around and stuff.

**Comment by RobertBohlman** [comment]
That's good, so did you touch the die() method in creature at all? I might just make one in player for quickness sake.

**Comment by ConorOHaleck** [comment]
Yeah, creature's have a Die() that removes them from the arraylist of stuff on the board. I don't know what Sam was talking about with ceasing to draw them on each iteration.

EDIT: Monsters rather

**Comment by RobertBohlman** [comment]
Whatever, I'm just going to have die for player that will flip a flag for a death message and a system.exit on key press. I'm tired as fuck and have a final in the morning.

**Comment by ConorOHaleck** [comment]
I hear you. I'll continue to work this one over, since I don't have a final in the morning except this one :P

**Comment by golbette** [comment]
Since they're not in the ArrayList, they won't be drawn on the board any more. That's what I meant :P

**Comment by ConorOHaleck** [comment]
Is that true for enemyList? Or should I be calling the appropriate part of testDungeon.populants?

**Comment by golbette** [comment]
They point to the same thing so ideally it shouldn't matter. Just use whatever you're using now

**Comment by RobertBohlman** [comment]
So, according to the red error text of death system.exit does't close everything in libgdx.

**Comment by golbette** [comment]
I would not recommend using system.out to close the program since that's just the console output stream. ( ͡° ͜ʖ ͡°)

gdx.app.exit(), also set config.forceExit = true in desktoplauncher class

**Comment by RobertBohlman** [comment]
Alright thanks, we can die now. Anything else y'all want me to look at before I go to bed? I have a test in the morning.

**Comment by golbette** [comment]
Hey Connor - try this in the enemy.move method - I don't know why but it worked for the player. Probably just a weird math bug 

![ss 2016-06-08 at 11 41 54](https://cloud.githubusercontent.com/assets/16601707/15920901/9f66cea2-2dd2-11e6-8ab8-40e6224cca4c.png)

**Comment by golbette** [comment]
Robert - I can't think of anything. I'll help Connor get his stuff working and we'll hopefully deploy tonight.

**Comment by RobertBohlman** [comment]
Alright thanks a ton, see ya tomorrow.

**Comment by ConorOHaleck** [comment]
So, my 2 problems right now are that:

1, That movement fix doesn't seem to have worked on the monsters, they're still showing up away from where they actually are (all our monsters are Displacer Dogs???)

And 2, killing something and removing it from the lists doesn't seem to stop it from existing. They appear to still be attacking and still taking damage and still drawn on the map and everything.

**Comment by golbette** [comment]
Weird. What's the exact amount of offset you're experiencing?

**Comment by ConorOHaleck** [comment]
1 tile. Always 1 tile. I've been testing using Wizard's Ice Lance to check all the tiles. Sometimes I have to aim up or down, or even in my own square.

**Comment by golbette** [comment]
One tile in what direction, or is it never consistent? e: I mean, your implication is that it's not consistent whoops?

**Comment by ConorOHaleck** [comment]
It isnt consistent, as far as I can tell. There are other issues with monsters taking too many turns, but that's in my own code (at least I think?), and I'm trying to find out where.

**Comment by golbette** [comment]
Try
`xPos = newTile.getx()*32;
 yPos = newTile.gety()*32;`

**Comment by ConorOHaleck** [comment]
```
public void move(Movement command){

    Tile oldTile;
    oldTile = MyGdxGame.testDungeon.getTileAt((this.xPos-Tile.WIDTH)/Tile.WIDTH, (this.yPos-Tile.HEIGHT)/Tile.HEIGHT);
    Tile newTile;
    newTile = MyGdxGame.testDungeon.getTileAt((((this.xPos-Tile.WIDTH)/Tile.WIDTH)+(command.x)), (((this.yPos-Tile.HEIGHT)/Tile.HEIGHT))+(command.y));


    if(!newTile.isCanCollide()){
        oldTile.setOccupant(null);
        oldTile.setCanCollide(false);

        xPos += Tile.WIDTH * command.x;
        yPos += Tile.HEIGHT * command.y;


        newTile.setOccupant(this);
        newTile.setCanCollide(true);
    }
    else{
        //Something upon bumping into something else?
    }
}
```

**Comment by ConorOHaleck** [comment]
"Movement" is a class that just has an x and y, in case that clarifies anything.

**Comment by golbette** [comment]
Do you mind pushing up what you've got so I can play with it, or would you rather keep your workflow untainted?

**Comment by ConorOHaleck** [comment]
I made the pull request, but Git is angry with me. I don't really know what I did wrong...

EDIT: Didn't commit to the branch before I made the request.

**Comment by golbette** [comment]
I can't even see the pull request on my end.

**Comment by ConorOHaleck** [comment]
It wants me to commit the changes made from like, 2 hours ago to my branch before it lets me do anything... Let me see if I can figure this out (got a backup file just in case)

**Comment by golbette** [comment]
Make a backup of your local work just in case, delete the branch (it should be purely abstract and not affect any actual work), commit your changes to a new branch and try to pull rq that?

**Comment by ConorOHaleck** [comment]
"Failed to delete Branch"... Can I force delete using the shell, or?

**Comment by golbette** [comment]
git branch -D (branchname) will force delete the branch

**Comment by ConorOHaleck** [comment]
What is the name of the branch, Monstrous_Branch? or is it one of those really long chains of characters?

Because it's giving me "Monstrous_Branch (or whatever) is not recognized as the name of a cmdlet, function, script file, or operable program"

**Comment by golbette** [comment]
yeha, it should just be Monstrous_Branch

**Comment by ConorOHaleck** [comment]
It basically won't let me do anything, with the reasoning "You have unmerged files, fix them up in the work tree"

**Comment by golbette** [comment]
Can you merge them?

**Comment by ConorOHaleck** [comment]
no, because it says there are conflicts...

**Comment by golbette** [comment]
Resolve the conflicts (ie, page through your code for broken files) and then add the files you fixed and merge.

Or just clone a new folder and paste your changed code files into it. I'm honestly not sure which will be less hassle at this point.

**Comment by golbette** [comment]
If you aren't having any luck, I can also look at the files with conflicts for you if you zip them up and send them to me.

**Comment by ConorOHaleck** [comment]
It was less hassle to knock it down and rebuild. I did it, its clean, its proper, you can check it out now if you want to.

**Comment by golbette** [comment]
I don't know what the hell you're passing into getTileAt() but it keeps crashing due to negative numbers.

**Comment by ConorOHaleck** [comment]
All it is is x or yPos/Tile.width or height

EDIT: I've been dealing with that too though

**Comment by golbette** [comment]
I'm going to be as honest as I can here and say I don't understand anything about your monster movement code other than basically nothing in it seems to work properly.

**Comment by ConorOHaleck** [comment]
All I did was get a number of set movements that are just x and y pairs. Look at Creature, under Movement, near the bottom. Movement UP is just a Movement with the x set to 0 and the y set to 1. If you pass that in as Move(UP), the thing should move 0 left or right but 32 pixels up.

**Comment by golbette** [comment]
I see now. I'm definitely not sure why this displacement is happening, but I think I can fix the crash.

**Comment by golbette** [comment]
I seem to have fixed it.

There are also instances where zombies stack on top of each other.

**Comment by golbette** [comment]
Okay, so it looks like whatever has changed on my end has fixed issues with enemies being in the wrong place, so I just need to fix the stacking problem in spawning.

**Comment by golbette** [comment]
Fixed that too, in a silly hacky way

**Comment by ConorOHaleck** [comment]
Speaking of which, I think I've found the root of most of my issues, which is that populateRooms doesn't work the way it should given the necessary changes I had to make to spawning

**Comment by golbette** [comment]
Yes. But despite this, there still seem to be enemies in empty tiles that have collision and make attacks.

**Comment by ConorOHaleck** [comment]
I am (almost) certain that's because populateRooms is generating a massive number of pseudo-enemies. I wondered why Trim()-ing the arraylist resulted in 530 enemies....

**Comment by golbette** [comment]
Hmm. I'll try reworking the function

**Comment by golbette** [comment]
Aha. It's because the function is setting dozens of ghost occupants.

**Comment by ConorOHaleck** [comment]
Spooky. But unfortunately we actually have an enemy for that...

**Comment by golbette** [comment]
Mk. I just decided what I'll do. Sit tight.

**Comment by golbette** [comment]
Okay. I've fixed phantom enemies AND collision displacement problems. Stand by for a fix to in-wall spawning.

**Comment by ConorOHaleck** [comment]
![](http://i.imgur.com/SENrL40.jpg)

I'm just gonna sit here doing stuff to make spawning all kinds of enemies work. It'll look better than just zombies.

**Comment by golbette** [comment]
![2egb2gl](https://cloud.githubusercontent.com/assets/16601707/15924803/e4564a90-2de8-11e6-8233-9b89eed2f6a9.png)

It's fixed for monsters!

All that's left is the player, and properly emptying out tiles with dead monsters in them.

**Comment by ConorOHaleck** [comment]
Awesome. I think I'm literally just going to do 3 kinds of undead, 3 kinds of ooze, and 3 kinds of dragon, and round out the spawner to allow for that. Also, I can hopefully undraw them using the Die() method.

**Comment by golbette** [comment]
Oh, I've already solved the Die() method too.

**Comment by ConorOHaleck** [comment]
![](http://i.imgur.com/RG0BS1U.gif)

Then I guess I don't have much to do but sort out my own monsters, if Die() scrubs em from the tile already. Know what they'd call you in Australia? A top bloke, that's what.

**Comment by golbette** [comment]
Yeah, so go ahead and pull the latest stuff, check it out, play with it a bit, and make any additions you like. I'll stick around for about an hour to try and catch any bugs that come up, then swing in in the morning for a release copy to deploy. 

 (I disabled the slowYourRoll() method because it was annoying to test with, and also the game felt better with it to me, but also I'm a former DCSS addict. It should still be commented somewhere.)

**Comment by golbette** [comment]
Also closing this because I think we solved this and about 5 other issues here.
