### ISSUE TITLE
You're welcome, all of you.

### ISSUE THREAD

**Issue by RobertBohlman** [ofHillsAndLakes/Daemon-Souls#4]
We present on Thursday. Please PLEASE realize we need every ounce of that time to get this completed.

**Comment by LaughingBarista** [comment]
Besides the functionGraphing project for CS, I really don't have much left to do. So I'm completely available to throw myself at whatever needs doing (including fixing up my own portion of the project as needed).. I also just noticed a rogue class was added; I'll add the assets for them probably tonight, if not tomorrow.

**Comment by golbette** [comment]
Fear not. If you look at my personal branch for the project, development
has been very much alive here.

**Comment by RobertBohlman** [comment]
Don't bother with rogue, I'm probably not going to finish it. Also Sam, when do you plan on pushing those changes? And as a note to everyone, I'm going to construct a schedule of what needs to get done (and in what order) to have the project ready two days before thursday (or tuesday for you normal folk).

**Comment by LaughingBarista** [comment]
Okay, I won't worry about rogue. I also pushed the goods to your branch, Sam just to be safe. Let me know what I can do to further it.

**Comment by golbette** [comment]
I'll take a look. Off the top of my head some UI art would be great since
we need that pretty badly. I'll be in during lab time tomorrow to talk too
if either of you are there!

**Comment by LaughingBarista** [comment]
I'll see you there!
