### ISSUE TITLE
Deployment File - Daemon Souls.jar

### ISSUE THREAD

**Issue by golbette** [ofHillsAndLakes/Daemon-Souls#42]
Take a look at this and let me know if it runs on your machine. Bonus points if you verify it working on a school machine! 
[daemon souls.zip](https://github.com/ofHillsAndLakes/Daemon-Souls/files/307693/daemon.souls.zip)

**Comment by ConorOHaleck** [comment]
Works on my machine without a hitch

**Comment by RobertBohlman** [comment]
On a school computer right now, testing.

**Comment by RobertBohlman** [comment]
Ooooh these computers actually have 7zip

Edit: Son of a bitch I don't have enough disk space.

**Comment by LaughingBarista** [comment]
Works on my machine as well beautifully. I do have one side note though: I've been forgetting this whole time to get a copy of the license(s) for assets involved and put them in a folder with the game file. I'm pretty sure I should do that..

**Comment by RobertBohlman** [comment]
That would require us to re-deploy the thing, and were just showing it to a small classroom.

**Comment by LaughingBarista** [comment]
Okay but before submission to the professor we should, yeah?

**Comment by RobertBohlman** [comment]
I don't think we are submitting it to him. But if he asks for it, yeah just tell him we need to submit a copy with the asset licenses.

**Comment by LaughingBarista** [comment]
Okay. Sounds good. What about in the gitHub file structure? I've never dealt with licenses before or their legal issues, to be honest..

**Comment by ConorOHaleck** [comment]
Well I don't think we'll be sued over our student project using mostly open-source material. But yeah, anywhere you can put the licenses works. Maybe replace what's in the Readme, since that's entirely vestigial now?

**Comment by RobertBohlman** [comment]
^ Yeh what he said.

**Comment by LaughingBarista** [comment]
Cool! Will do! .... after class. See you guys there! (By the way, I'm still horrendous at presenting, so I might not say much; I'm sorry).

**Comment by golbette** [comment]
Ran the .jar on an information commons computer with no issues. 

I've added a version of the Apache 2.0 license to the game folder in compliance with libgdx's licensing rules. Not a lawyer, but it basically just reads "this shit is free to use and modify as long as you include a copy of this license informing other people that it's free to use and modify along with documentation of any significant changes to the codebase you received." (we didn't alter libgdx, so there's none)
