### ISSUE TITLE
Project Task Schedule.

### ISSUE THREAD

**Issue by RobertBohlman** [ofHillsAndLakes/Daemon-Souls#5]
Since so many of our tasks are dependent on one another's, I'm going to be listing the dates by which we need to have our individual jobs done so we can have the project ready by a reasonable time. When I list a date, I'm referring to the end of that day (so midnight).

Friday(6/3)- Missing job class Skills- Me. | Map drawing cleanup- Sam (I posted about this on the last merge).
Saturday(6/4)- Facing and melee ability targeting- Me. | Basic code for items and inventory- Connor.
Sunday(6/5)-  Sprite drawing - David. | Ranged targeting- Me | Basic UI - Sam
Monday(6/6)- Animations- David. | Monsters- Connor. | Cooldowns and round timers- Me | Wizard teleport- Me
Tuesday-Wednesday(6/7-8)- Bug fixes, deployment, and extra content.

*Note, the UI needs to include in game, but we also need a way to select what class to play as when the game starts. 

Edit(6/2): David I remember you put together a small list of stuff for yourself today, it doesn't really matter when you get it done so long as you get the stuff listed here done on time.

The goal is to have the game presentable by Tuesday. If this contradicts with what anyone was currently working on or has done already (Sam I saw you said you were working on stuff I just don't know what), let me know and I'll update the schedule. The idea though is that we can count on each other to have things set up by certain dates so the next person can build off of it. I'll post a link to this on canvas so everyone sees it. Finally, can I please ask that you all try to make it to class daily this week? We have no real easier ways of communicating. Talking is a lot more efficient than text tag.

**Comment by golbette** [comment]
Hey Robert,

Well, just so you know, dungeon generation is done. Some elements of tile
organization are done as well. You can see a log of my personal branch
here, which will likely be merged tomorrow once I'm sure the classes are
stable:

https://github.com/golbette/Daemon-Souls

Rather than worrying about linear single collection math, I just went ahead
and gave each Tile() an X,Y index. This should make it very easy to detect
when the player is going to occupy the same tile as an enemy. They are
still stored as a linear list, but this means you can also get each tile as
a two dimensional vector.

**Comment by LaughingBarista** [comment]
Thanks for posting to canvas, I can see that a lot faster. I 'll come to class. If you do have any urgent needs though, you could just call/text me at (253) 381-5408. Nice code, Sam. I'll need to change a couple things on my end to fit with what you have, but I've already committed my changes.

**Comment by golbette** [comment]
Push your changes if you haven't, and it should be easy for us to merge
them with my branch using a pull request~. Any conflicts in the main game
loop on my end will be discarded, they're just for debugging the map

**Comment by LaughingBarista** [comment]
Hmmm.. I though I did. I will try again.

**Comment by golbette** [comment]
It's there, so don't worry about it, I was just saying in case you didn't
if I hadn't checked

**Comment by RobertBohlman** [comment]
Alright, well I typed this up right when I got off from work and now that i've showered and had food im like half asleep so ill update the list tomorrow.

**Comment by RobertBohlman** [comment]
I want to add something I forgot to mention before, David, do you think you could also manage to get some timers to wait at the end of turns set up? That way the player will have time to read the combat log. Let me know if you can and I'll update the schedule.

**Comment by LaughingBarista** [comment]
I'll add it to my to do list. Prioritization-wise, would that be before or after UI?

**Comment by RobertBohlman** [comment]
Technically the UI would be higher, but it really shouldn't take that long so you may as well do it first, helps with testing combat too.

**Comment by LaughingBarista** [comment]
![gamenotworking](https://cloud.githubusercontent.com/assets/15771896/15801482/4b3d1cc6-2a4b-11e6-9074-88ed5485c221.PNG)

**Comment by LaughingBarista** [comment]
I'm trying to get the base game to run so that I can emulate the way you guys have been instantiating new players (etc) to add my assets/animations.. While trying to make my code play nice with yours last night, I felt I was changing wayyyy too much of what you guys had done, and that doesn't feel right to me.

**Comment by RobertBohlman** [comment]
![untitled](https://cloud.githubusercontent.com/assets/12433391/15801877/93bbe958-2a57-11e6-9c44-15fda88db16a.png)

So what I did to fix it was go to run configuration and make sure I had the proper assets folder selected.

**Comment by RobertBohlman** [comment]
Sam did you ever get any word from Connor about what he's doing?

**Comment by LaughingBarista** [comment]
Hey thanks so much! :sweat_smile:

**Comment by RobertBohlman** [comment]
By the way, you should probably re-clone the repository, since two pushes came out.

**Comment by LaughingBarista** [comment]
I did, no worries.

**Comment by ConorOHaleck** [comment]
![example](https://cloud.githubusercontent.com/assets/12401546/15803649/a9065e6e-2a9e-11e6-9ccd-fd13db17161b.png)

Goodness lord, I finally got Github, Eclipse, and the project all working together. In true software development tradition, I have no earthly idea what broke or how I fixed it, only that it works now.

Only question I have is why we have a selection of complete-ish looking classes all arranged together in the my-gdx-game-core thing, and then a bunch of other class outside that in the basic folder, that don't seem to have much work done with them at all (see Fig 1). Is that just vestigial from an earlier piece of code, or is deleting that going to wreck everything?

**Comment by RobertBohlman** [comment]
I wouldn't mess with them if I were you, I trust you can read the schedule, so you know what you need to get done.

**Comment by ConorOHaleck** [comment]
Yup. I'm thinking items simply modify a stat or change a flag boolean on pickup, and reverse that on dropoff, There SHOULD be no earthly way to possibly get rid of an item without going through the Drop() function (or whatever it ends up being) so you can't somehow infinitely stack items. Also, having a lot of fun conceptualizing different monster concepts.

"Monster" conceptualizes basic AI, stuff like "aiEngage" which moves them closer to the player, "aiRetreat" which makes them move away, "aiWander" which is before the player even sees them and they're just stumbling around. Individual monsters call these methods in different scenarios.

"Undead" are the simplest and the dumbest. Besides varying hp/attack/armor levels, none of them do anything remarkable. They run towards the player and try to hit him to death.

"Goblin"s are unique in that they give buffs to any other Goblin nearby, and have different types, which all fit the scheme of "-obGoblin", (ie Hobgoblin, Snobgoblin, Sobgoblin, Robgoblin, and so on) Some try to attack you while others stay away, continually dispensing buffs.

"Golem"s have large auras that cause effects around them, depending on the type.

"Ooze"s have a chance to split into multiple Oozes. Some Oozes do it when attacked, others just have a percent chance to multiply or do it every X turns or so.

"Dragon"s just kill you outright. Better hope one doesn't spawn in front of you.

etc etc etc, all rattling around in my head

**Comment by RobertBohlman** [comment]
Sounds good, I made a little imp testing enemy to give Sam something to populate rooms with but feel free to delete that since I didn't make the design super modular.

**Comment by RobertBohlman** [comment]
Updated, though it was more a public note-to-self.
