### ISSUE TITLE
Help with determining class type when using skills.

### ISSUE THREAD

**Issue by RobertBohlman** [ofHillsAndLakes/Daemon-Souls#8]
![image](https://cloud.githubusercontent.com/assets/12433391/15802375/a40698aa-2a64-11e6-84c2-ac44ebddb477.png)

Good news everyone! I've got the melee targeting working beautifully! However, I'm having trouble with having the program use the right skill depending on what testPlayer was instantiated as. I can't seem to cast across classes on the same level of hierarchy. I'm going to take a break and meditate on this, but if anyone has any suggestions, feel free to drop them here. Don't worry, even if I can't get this working, I still have melee targeting and it works fine if I just use one class (i.e. Knight) so expect a push tonight.

**Comment by RobertBohlman** [comment]
Fyi, the error reads that stab is not a method in Barbarian, which is what testPlayer currently is being instantiated as in the create() method.

**Comment by golbette** [comment]
Since you're already safe by checking instanceof/typeof/something similar, is it possible to cast the testPlayer as its appropriate type before calling the function?

**Comment by RobertBohlman** [comment]
No, I get the error: "Barbarian cannot be cast to Knight."

**Comment by RobertBohlman** [comment]
Alright I fixed it, though the solution was a bit silly. By passing in testPlayer as a player argument, I effectively cast the job class type into a player which could then be cast into whatever subclass it needed to be. Weird, but it makes sense and it worked.

I'll be closing this.
